import numpy as np
print(np.float_power(49, 0.5), " ")
print(np.float_power(2, 0.2), " ")
print(np.float_power(44.5, 5/9), " ")
print(np.sin((5*np.pi)/4) , " ")
print(np.sqrt(3) , " ")
print(np.float_power((5.654 * np.float_power(10, 24)), 1/7) , " ")
print(np.pi * 4 , " ")
print(np.cos((-3* np.pi)/5), " ")
print(np.tan(np.deg2rad(77)), " ")
print(np.arccos(34.1) , " ")
print(np.e , " ")
print(np.log10(23) , " ")
print(np.arccos(-0.45) , " ")
print(np.float_power(np.e, -3.34), "")
print(np.log(13.2) , " ")
print(np.log2(69.6))